### ISSUE TITLE
Matematicas discretas. Practica 7

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Proyect-A16#1]
[Matematicas discretas Practica 7.0.pdf](https://github.com/user-attachments/files/17483949/Matematicas.discretas.Practica.7.0.pdf)

**Comment by Juan27231** [comment]
Portada 5/5
Procedimientos 4/5
lista de figuras 5/5
Resultados y conclusiones 5/5
Calificación 19/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
